version: "2"
services:
  node:
    image: 059402281999.dkr.ecr.ap-northeast-1.amazonaws.com/goodjob/goodjobshare:stage
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - API_HOST=https://tranquil-fortress-92731.herokuapp.com
        - CONTENTFUL_API_HOST=https://content-stage.goodjob.life
        - FACEBOOK_APP_ID=1844389232511081
    ports:
      - 39000:3001
