version: "2"
services:
  node:
    image: 059402281999.dkr.ecr.ap-northeast-1.amazonaws.com/goodjob/goodjobshare:production
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - API_HOST=https://api.goodjob.life
        - CONTENTFUL_API_HOST=https://content.goodjob.life
        - FACEBOOK_APP_ID=1750216878594984
        - GA_ID=UA-79990667-1
        - PIXEL_ID=603414113402034
    ports:
      - 42000:3001
